server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/twinzpay_user_db
    username: root # Change this to your MySQL username
    password: 1234qwer # Change this to your MySQL password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


jwt:
  # This must be a long, complex, Base64-encoded string in production.
  # For local development, this 256-bit string will work.
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 1 day in milliseconds

# Add this at the root level of your file
springdoc:
  api-docs:
    path: /api/v1/users/v3/api-docs