server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/twinzpay_user_db
    username: ${DB_USERNAME} # Change this to your MySQL username
    password: ${DB_PASSWORD} # Change this to your MySQL password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


jwt:
  # This must be a long, complex, Base64-encoded string in production.
  # For local development, this 256-bit string will work.
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION} # 1 day in milliseconds

# Add this at the root level of your file
springdoc:
  api-docs:
    path: /api/v1/users/v3/api-docs